### ISSUE TITLE
Where's the wiki?

### ISSUE THREAD

**Issue by roccomuso** [sui77/rc-switch#12]
How do we know which remotes are supported?

Brennenstuhl RCS 1000 N are supported?

**Comment by roccomuso** [comment]
Confirmed. Brennenstuhl RCS 1000 N and Arendo outplugsboth works fine.

**Comment by fingolfin** [comment]
I used the Google Code export feature to migrate the Wiki. You can find my version of it (with various cleanups already applied) here: 
  https://github.com/fingolfin/rc-switch/wiki

Since GitHub stores the Wiki as a another git repository (see https://github.com/fingolfin/rc-switch.wiki.git), it should be easy for @sui77 to add his wiki back to this repository, if he wants to.

**Comment by fingolfin** [comment]
Oh, and this also migrated the issues. Just sayin'

**Comment by sui77** [comment]
If only i knew how to do that. I'm still not very used to git... I've added you as Collaborator, could you do that?

**Comment by fingolfin** [comment]
The first step for this requires admin access, so I can't do it, but it's also very easy: just go to the "Settings" page for this repo (i.e. https://github.com/sui77/rc-switch/settings) and enable the Wiki.
This will make a wiki link appear. Click on it, then follow the instructions to create the first page.

Once that is done, I can continue, but you can also do it yourself, it's not hard (once you know how, at least ;-): Basically, just clone your wiki https://github.com/sui/rc-switch.wiki.git  then copy the data from my version of the wiki (cloned from https://github.com/fingolfin/rc-switch.wiki.git). One can also be more fancy and also copy the history of changes I made, but that's not so important (though I'll do it, if you want, it'll only take me a few seconds)

**Comment by sui77** [comment]
enabled but didn't even managed to check it out. feel free to copy/merge/import(?) yours.
danke :)

**Comment by fingolfin** [comment]
Seems you missed this part of the instructions (and/or did not complete them): "Click on it, then follow the instructions to create the first page." -- this creates the Wiki repository.

Anyway, I now did that, and also transferred the Wiki. Note that I already edited it a little bit compared to what is on Google Code -- in particular, I copied all pictures, instead of relying on links to external sites (which might vanish...)
